CentOS replaced by RHEL
RedHatInsights/s2i-insights-compliance pull request #5
Opened 2019-03-18 12:53 UTC by quarckster

2019-03-18 14:41 UTC, akofink requested changes
This doesn't seem to "just work". I'm having trouble getting the `epel-release` package to be available, despite enabling the rhel-7-server-extras repo on the host system. I'm not really sure if there's anything we can do in this dockerfile, or if we just have to have the right subscriptions/repos enabled. :man_shrugging:

2019-03-18 14:54 UTC, quarckster commented
@akofink could you please test the latest commit. I didn't realize that RHEL enables EPEL in a different way.

2019-03-18 15:02 UTC, akofink approved these changes
Works just like centos used to. ACK!

2019-04-12 12:52 UTC, dLobatog approved these changes

2019-04-12 12:53 UTC, merged